name: Build ecampus.kpi.ua

on:
  push:
    branches:
      - ua-v3

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        logout: true

    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        repository: ${{ github.repository }}

    - name: Build Docker image
      run: |          
        now=$(date +%Y%m%d%H%M%S)
        tag1="kpiua/ecampus-kpi-ua:ui-v3-$now"
        tag2="kpiua/ecampus-kpi-ua:ui-v3-latest"
        
        docker build ./ --file ./.dockerfile --tag $tag1 --tag $tag2
        
        docker push $tag1
        docker push $tag2